# Generated by Django 5.2 on 2025-04-26 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('longitude', models.PositiveIntegerField()),
                ('latitude', models.PositiveIntegerField()),
                ('description_texte', models.TextField()),
                ('description_vocale', models.FileField(upload_to='')),
                ('etat', models.CharField(choices=[('AT', 'En Attente'), ('TR', 'Traite')], default='AT')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidents.categorie')),
            ],
        ),
    ]
